import "./globals.css";
import { Kalnia } from 'next/font/google'

const kalnia = Kalnia({
    subsets: ['latin'],
    display: 'swap', 
})

export const metadata = {
  title: "Raelyn A.",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1 className={kalnia.className}>
        {children}
        </h1>
      </body>
    </html>
  );
}
